The cause of error seems is the line contains multibyte words. The message is as below.
Traceback (most recent call last):
  File "/Users/XXX/.neobundle/jedi-vim/jedi_vim.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/Users/XXX/.neobundle/jedi-vim/jedi_vim.py", line 252, in show_call_signatures
    signatures = get_script().call_signatures()
  File "/Users/XXX/.neobundle/jedi-vim/jedi/jedi/api/__init__.py", line 555, in call_signatures
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/XXX/.neobundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
    result = func(self)
  File "/Users/XXX/.neobundle/jedi-vim/jedi/jedi/parser/user_context.py", line 237, in user_stmt_with_whitespace
    pos = next(self._user_context.get_context(yield_positions=True))
  File "/Users/XXX/.neobundle/jedi-vim/jedi/jedi/parser/user_context.py", line 159, in get_context
    if line[pos[1] - 1].isspace():
IndexError: string index out of range